### ISSUE TITLE
UC8 - Procedure developed in R should be transferred to python

### ISSUE THREAD

**Issue by christianbriese** [openEOPlatform/SRR3_notebooks#6]
@mattia6690 UC8 - Procedure developed in R should be transferred to python to make such an approach visible to users: "to obtain the test sites the study area is divided in a regular grid each containing roughly 40.000 16 ha sites"  -- Especially

**Comment by clausmichele** [comment]
The notebook draft is here https://github.com/openEOPlatform/SRR3_notebooks/blob/main/notebooks/UC8_local_sampling.ipynb

**Comment by basu26** [comment]
The final notebook is here https://github.com/openEOPlatform/SRR3_notebooks/blob/main/notebooks/UC8_local_sampling.ipynb
